### ISSUE TITLE
How click to intents ??

### ISSUE THREAD

**Issue by helmifluida** [Tarekajaj/WhatsappMenuReplicate#1]
How create every button click to menu intent

**Comment by Tarekajaj** [comment]
```
public void menuClick(View view){
    hideMenu();
    Toast.makeText(this, view.getTag() + " Clicked", Toast.LENGTH_LONG).show();
}
```

when you click on a menu item this function gets fired. you ca either use a **switch case** on the **view.getTag()** to handle each menu item separately, or you can edit the _layout_ file and set a different _onClick_ function for each item. whatever suit you best.

#####Please Note that this is simply an experiment
